name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Test
        run: ls target/release
      - name: Move Target
        run: mv target/release/okane .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: okane
          draft: true
